// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfQABFJAs4koYQ7rLJJpGtUCX9vqn7EaA',
    appId: '1:404029141436:web:28153bbd01d1da69c1fbb9',
    messagingSenderId: '404029141436',
    projectId: 'flutter-crud-d7b69',
    authDomain: 'flutter-crud-d7b69.firebaseapp.com',
    storageBucket: 'flutter-crud-d7b69.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIGg9hQb6eLno2BR5cYG1nmfmR5bstdyE',
    appId: '1:404029141436:android:09731fbd37606118c1fbb9',
    messagingSenderId: '404029141436',
    projectId: 'flutter-crud-d7b69',
    storageBucket: 'flutter-crud-d7b69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-aGE0OfoS8ncWtbUzPtco_vIhB2QpI_k',
    appId: '1:404029141436:ios:fbe910d3c0abd8c3c1fbb9',
    messagingSenderId: '404029141436',
    projectId: 'flutter-crud-d7b69',
    storageBucket: 'flutter-crud-d7b69.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-aGE0OfoS8ncWtbUzPtco_vIhB2QpI_k',
    appId: '1:404029141436:ios:fbe910d3c0abd8c3c1fbb9',
    messagingSenderId: '404029141436',
    projectId: 'flutter-crud-d7b69',
    storageBucket: 'flutter-crud-d7b69.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfQABFJAs4koYQ7rLJJpGtUCX9vqn7EaA',
    appId: '1:404029141436:web:c77bee0a527d9a37c1fbb9',
    messagingSenderId: '404029141436',
    projectId: 'flutter-crud-d7b69',
    authDomain: 'flutter-crud-d7b69.firebaseapp.com',
    storageBucket: 'flutter-crud-d7b69.firebasestorage.app',
  );
}
